# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{google-translate}
  s.version = "0.7.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Shvets"]
  s.date = %q{2010-09-16}
  s.description = %q{Simple client for Google Translate API.}
  s.email = %q{alexander.shvets@gmail.com}
  s.executables = ["translate", "t"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "CHANGES",
     "README",
     "Rakefile",
     "VERSION",
     "bin/t",
     "bin/t.bat",
     "bin/translate",
     "bin/translate.bat",
     "google-translate.gemspec",
     "lib/google_translate.rb"
  ]
  s.homepage = %q{http://github.com/shvets/google-translate}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.requirements = ["none"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple client for Google Translate API (Summary).}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/translate_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json_pure>, [">= 1.1.4"])
      s.add_runtime_dependency(%q<json_pure>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<gemcutter>, [">= 0"])
    else
      s.add_dependency(%q<json_pure>, [">= 1.1.4"])
      s.add_dependency(%q<json_pure>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<gemcutter>, [">= 0"])
    end
  else
    s.add_dependency(%q<json_pure>, [">= 1.1.4"])
    s.add_dependency(%q<json_pure>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<gemcutter>, [">= 0"])
  end
end

